# Site settings
title: 3Dogs Walking
email: your-email@domain.com
baseurl: /jksite/
description: "Write an awesome short description for your new site here. We are a foo business that provides bar, and baz services."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 3Dogs Walking

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com
  - title: facebook
    url: https://facebook.com
  - title: pinterest
    url: https://pinterest.com

# Build settings
markdown: kramdown
permalink: pretty
